03 lection1  button
js-tasks-ru/htmlcss-20220317_zurab pull request #5
Opened 2022-03-23 22:34 UTC by Zurab-D

2022-03-23 22:34 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-03-24 14:43 UTC, GSemikozov requested changes

2022-03-24 14:43 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.buttons p {
в файле компонента можно добавлять только стили этого компонента + его элементы и модификаторы. А .buttons - это уже другой блок в который мы вкладываем данный. Если это просто вспомогательные стили и нужно только для страницы с примером - тогда такие стили можно оформлять прямо в теге style хтмл страницы

2022-03-24 14:43 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  padding: 15px;
по дизайну 15px 15px 14px

2022-03-24 14:43 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  font-size: 16px;
не хватает font-family

2022-03-24 14:43 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  cursor: default;
pointer-events: none; по умолчанию сделает cursor: default;

2022-03-24 14:43 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button--prymary {
модифицированный БЭМ не обсуждали (например, модификатор через `--` вместо `_`) - из личного опыта идея?)

2022-03-24 15:04 UTC, Zurab-D commented on 03-lection1/01-button/button.css
> +  font-size: 16px;
Так у нас же в main.css прописано:
`* {
    font-family: 'Roboto', sans-serif;
    box-sizing: border-box;
}
`

2022-03-24 15:07 UTC, Zurab-D commented on 03-lection1/01-button/button.css
> +.button--prymary {
У нас на работе верстальщики так пишут, глаз уже привык )

2022-03-24 15:10 UTC, Zurab-D commented on 03-lection1/01-button/button.css
> +  font-size: 16px;
Или нужно в самом блоке обязательно прописывать? Я не стал указывать из той мысли, что если на другой странице фонтом по умолчанию или фонтом родителя будет другой, то он автоматически подхватится

2022-03-24 15:15 UTC, Zurab-D commented on 03-lection1/01-button/button.css
> +.buttons p {
Поправил

2022-03-24 15:16 UTC, Zurab-D commented on 03-lection1/01-button/button.css
> +  padding: 15px;
поправил

2022-03-24 15:17 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-03-24 15:18 UTC, Zurab-D commented on 03-lection1/01-button/button.css
> +  cursor: default;
поправил

2022-03-25 19:45 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  font-size: 16px;
у нас в проекте будет как минимум 3 разных шрифта, и наследоваться мы будет не всегда об body, по этой причине на уровне блока лучше явно прописать какой именно шрифт используется

2022-03-25 19:46 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button--prymary {
я не против такой модификации, но тогда важно соблюдать это соглашение по всему проекту)

2022-04-03 11:29 UTC, Zurab-D commented on 03-lection1/01-button/button.css
> +.button--prymary {
ok

2022-04-03 11:37 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-04-03 13:03 UTC, Zurab-D commented on 03-lection1/01-button/button.css
> +  font-size: 16px;
поправил

2022-04-03 17:40 UTC, GSemikozov approved these changes

2022-04-03 17:40 UTC, merged