05 lection3  01 tooltip
js-tasks-ru/htmlcss-20220317_zurab pull request #9
Opened 2022-04-05 23:30 UTC by Zurab-D

2022-04-05 23:31 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-04-06 18:09 UTC, GSemikozov requested changes

2022-04-06 18:09 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +    position: relative;
вот здесь прям обязательно inline-block )

2022-04-06 18:09 UTC, GSemikozov commented on 05-lection3/01-tooltip/index.html
> +                <div class="tooltip__text-container" style="width: 130px;">
инлайн здесь будет лишним

2022-04-06 18:28 UTC, Zurab-D commented on 05-lection3/01-tooltip/tooltip.css
> +    position: relative;
поправил

2022-04-06 18:28 UTC, Zurab-D commented on 05-lection3/01-tooltip/index.html
> +                <div class="tooltip__text-container" style="width: 130px;">
убрал

2022-04-06 18:49 UTC, GSemikozov approved these changes

2022-04-06 18:49 UTC, merged